# Config file for automatic testing at travis-ci.org

language: minimal
sudo: false
notifications:
  # email: false


matrix:
  fast_finish: true
  include:
  - env: CONDA_ENV=py36
  - env: CONDA_ENV=py37

before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda info -a

install:
  - conda env create -n pyfesom2 --file ci/requirements-$CONDA_ENV.yml
  - source activate pyfesom2
  - conda list
  - pip install --no-deps -e .


script:
  - which python
  - python --version
  - python -OO -c "import xarray"
  - pytest

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
# deploy:
#   provider: pypi
#   distributions: sdist bdist_wheel
#   user: koldunovn
#   password:
#     secure: PLEASE_REPLACE_ME
#   on:
#     tags: true
#     repo: koldunovn/pyfesom2
#     python: 3.6
