name: pyfesom2 ollie test
# Controls when the action will run. Triggers the workflow on push or pull request.

on: [push]

jobs:
    #  example-1:
    #    name: ollie ${{ matrix.module }}
    #    runs-on: hpc_awi_ollie
    #    strategy:
    #      fail-fast: false
    #      matrix:
    #        module:
    #            - python3/3.6.3-intel2018
    #            - python3/3.6.5_intel2019
    #            - python3/3.7.10_intel2021
    #            - python3/3.7.7_intel2020
    #            - python3/3.7.7_intel2020u2
    #    steps:
    #      - uses: actions/checkout@v2
    #      - name: Run Test ${{ matrix.module }}
    #        shell: bash -l {0}
    #        run: |
    #            module load ${{ matrix.module }}
    #            module list
    #            pip install --user -e .
    #            pip install --user pytest
    #            pytest
  miniconda:
    name: ollie miniconda installation
    runs-on: hpc_awi_ollie
    env:
        CONDA: "/home/ollie/abtci/miniconda"
        PATH: "/home/ollie/abtci/miniconda/bin:/home/ollie/abtci/miniconda/condabin:/usr/lib64/qt-3.3/bin:/cm/local/apps/environment-modules/4.0.0/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/sbin:/cm/local/apps/environment-modules/current/bin:/opt/munge/default/bin:/global/opt/slurm/default/bin:/global/AWIsoft/bin:/home/ollie/abtci/bin:/global/AWIsoft/bin:/home/ollie/abtci/bin"
        TMPDIR: "/work/ollie/tmp"
        TMP: "/work/ollie/tmp"
        WORK: "/work/ollie/abtci"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
            auto-update-conda: true
            activate-environment: pyfesom2
            environment-file: ci/requirements-py37.yml
            channels: conda-forge
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Install
        shell: bash -l {0}
        run: pip install -e .
      - name: Test
        shell: bash -l {0}
        run: pytest

