# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Publish Package
permissions:
  id-token: write
on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if ${{ matrix.python-version == '3.12' }}; then pip install --upgrade setuptools; fi
      - name: Install package
        run: |
          python -m pip -e .
      - name: Test with pytest
        run: |
          pytest
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build package
        run: |
          python -m build
  publish-pypi:
    name: Publish on PyPI
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/p/pyfesom2
    steps:
      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@release/v1
  publish-conda-forge:
    name: Publish on conda-forge
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: conda-forge-publish
        uses: fcakyon/conda-publish-action@master
        with:
          subdir: 'conda'
          anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
          platforms: 'win osx linux'
