name: pyfesom2 main test

# Controls when the action will run. Triggers the workflow on push or pull request.

on: [push]

jobs:
  update_requirements_and_try_conda:
      name: Main Test
      runs-on: "ubuntu-latest"
      steps:
        - uses: actions/checkout@v2
        - uses: pgierz/pipreqs-action@pip
        - uses: pgierz/pipreqs-action@conda
          with:
            CONDA_REQS: ci/requirements-py37.yml
        - uses: actions/checkout@v2
        - uses: conda-incubator/setup-miniconda@v2
          with:
            auto-update-conda: true
            activate-environment: pyfesom2
            environment-file: ci/requirements-py37.yml
            python-version: "3.7"
            channels: conda-forge
            auto-activate-base: false
            show-channel-urls: true
            # use-only-tar-bz2: true
            allow-softlinks: true
        - name: Install
          shell: bash -l {0}
          run: pip install -e .
        - name: Test
          shell: bash -l {0}
          run: pytest
