name: pyfesom2 ollie test
# Controls when the action will run. Triggers the workflow on push or pull request.

on: [push]

jobs:
  example-1:
    name: Ex1 (ollie ${{ matrix.module }})
    runs-on: hpc_awi_ollie
    strategy:
      fail-fast: false
      matrix:
        module:
            - python/2.7.14-intel2018(default)
            - python/2.7.14-intel2018_no_ld_library_path
            - python3/3.6.3-intel2018
            - python3/3.6.5_intel2019
            - python3/3.7.7_intel2020
            - python3/3.7.7_intel2020u2(default)
            - python3/3.7.10_intel2021
            - anaconda2/4.0.0
            - python/2.7-intel2017.0.035
            - python/2.7.10-intelbeta
            - python3/3.5-intel2017
            - python3/3.5-intelbeta
    steps:
      - uses: actions/checkout@v2
      - name: load ollie ${{ matrix.module }}
        shell: bash -l {0}
        run: module load ${{ matrix.module }}
      - name: Install
        shell: bash -l {0}
        run: |
            module list
            pip install -e .
      - name: Test
        shell: bash -l {0}
        run: |
            module list
            pytest

